#!/usr/bin/env bash
# Print per-domain sudoers lines for commands that take a domain, so no
# sudoers wildcard is ever needed. Usage:
#   scripts/gen-sudoers.sh example.com shop.example.net > /tmp/hostops-domains
#   visudo -cf /tmp/hostops-domains && install -m 0440 /tmp/hostops-domains /etc/sudoers.d/hostops-domains
set -euo pipefail

domain_re='^([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$'
(( $# > 0 )) || { echo "usage: $0 <domain>..." >&2; exit 3; }

cert=() backup=()
for d in "$@"; do
  [[ "$d" =~ $domain_re ]] || { echo "invalid domain: $d" >&2; exit 3; }
  cert+=("/root/.acme.sh/acme.sh --renew -d $d --force --server letsencrypt --ecc" \
         "/root/.acme.sh/acme.sh --renew -d $d --force --server letsencrypt")
  backup+=("/usr/bin/cyberpanel createBackup --domainName $d --backupPath /home/backup")
done

join() { local IFS=$'\n'; printf '%s' "$*" | sed ':a;N;$!ba;s/\n/, \\\n    /g'; }
echo "# generated by scripts/gen-sudoers.sh on $(date -u +%Y-%m-%d)"
echo "Cmnd_Alias HOSTOPS_CERT_D = $(join "${cert[@]}")"
echo "Cmnd_Alias HOSTOPS_BACKUP_D = $(join "${backup[@]}")"
echo "hostops ALL=(root) NOPASSWD: HOSTOPS_CERT_D, HOSTOPS_BACKUP_D"
